### ISSUE TITLE
NPM Release does not contain 'dist'

### ISSUE THREAD

**Issue by chrisspiegl** [ismailnguyen/vue-dark-mode-switch#1]
Default import does not work because `dist` folder is not part of the NPM package.

Using `import DarkModeSwitch from 'vue-dark-mode-switch/src/main'` does work for now though 🌸.

**Comment by ismailnguyen** [comment]
Hi @chrisspiegl ,

Did you tried to import using ```import DarkModeSwitch from 'vue-dark-mode-switch'``` ?

By the way i've just pushed the dist file, thank you ;)

**Comment by chrisspiegl** [comment]
Hi @ismailnguyen , yes the std import is what I tried but since the `main` is set to the `dist` folder and that was not present it did not work.
Thanks for pushing the change so quickly. 

Interestingly, for me it actually works better when I keep importing the `src/main` myself. This may be because I am using the `vite` and `vuejs 3` environment and that can traverse the environment itself to build the proper files.

Again, thanks and I am looking forward to using this component 👍 .
